### ISSUE TITLE
Docs: mention the `sleep_time` kwarg

### ISSUE THREAD

**Issue by DilumAluthge** [JuliaLinearAlgebra/BLASBenchmarksCPU.jl#21]
I imagine that for users that run `BLASBenchmarksCPU.runbench` on their laptops, it won't be uncommon to see people running into thermal throttling.

Does setting a positive value for `sleep_time` help address that? If so, we should add a section or page to the docs that explains this.

**Comment by chriselrod** [comment]
I think [this](https://chriselrod.github.io/BLASBenchmarksCPU.jl/dev/turbo/) is a better solution, although it'd be nice to add sections for Mac and Windows.

But we could make a note of that in that section, and perhaps generalize the section to "Consistent Benchmarking".

**Comment by DilumAluthge** [comment]
Let's close this, but we can keep thinking of ways to improve https://julialinearalgebra.github.io/BLASBenchmarksCPU.jl/dev/turbo/
