### ISSUE TITLE
MethodError: no method matching mkl_set_num_threads(::Static.StaticInt)

### ISSUE THREAD

**Issue by vandenman** [JuliaLinearAlgebra/BLASBenchmarksCPU.jl#79]
~Since [this commit in JuliaSIMD/CPUSummary.jl](https://github.com/JuliaSIMD/CPUSummary.jl/commit/b9ae037826c1112a7c727d5e9e5edec1e420f050) it looks like BLASBenchmarksCPU.jl is broken?~

Edit: the bug is probably caused by a change in Static.jl where it no longer subtype base types to avoid invalidations (see https://github.com/SciML/Static.jl/issues/73 and the README of Static.jl)

Basically,

- `CPUSummary.num_cores()` returns a `Static.StaticInt`.
- `Static.StaticInt` is not a subtype of `Integer`.
- `mkl_set_num_threads(N::Integer)` and all other `XXX_set_num_threads(N::Integer)` throw a MethodError.

Possible fix:

change the argument to
```diff
-function mkl_set_num_threads(N::Integer)
+function mkl_set_num_threads(N::Union{Integer, Static.StaticInt})
```
likewise for all other `XXX_set_num_threads`. 

I'd be happy to open a PR if this is a reasonable solution!

**Comment by chriselrod** [comment]
Yes, spot on. PRs welcome.
